<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Tempo</Title>
    <Authors>jchristn</Authors>
    <Description>Placeholder</Description>
    <Copyright>(c)2025 Joel Christner</Copyright>
    <PackageProjectUrl>https://github.com/jchristn/tempo</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jchristn/tempo</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="Padlock" Version="1.0.0" />
    <PackageReference Include="PrettyId" Version="2.0.0" />
    <PackageReference Include="RestWrapper" Version="3.1.8" />
    <PackageReference Include="SyslogLogging" Version="2.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Runners\" />
  </ItemGroup>

</Project>
