<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591;CS8618</NoWarn>
    <AssemblyName>Tempo.Server</AssemblyName>
    <RootNamespace>Tempo.Server</RootNamespace>
    <Version>0.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Watson" Version="7.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tempo.Core\Tempo.Core.csproj" />
    <ProjectReference Include="..\Tempo.Sample.DotnetProcess\Tempo.Sample.DotnetProcess.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tempo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="clean.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="clean.sh">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyTempoDotnetProcessSample" AfterTargets="Build" Condition="'$(TargetFramework)' != ''">
    <ItemGroup>
      <TempoDotnetProcessSampleFiles Include="..\Tempo.Sample.DotnetProcess\bin\$(Configuration)\$(TargetFramework)\**\*.*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(TempoDotnetProcessSampleFiles)"
      DestinationFiles="@(TempoDotnetProcessSampleFiles->'$(TargetDir)Samples\DotnetProcess\%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
